# Generated by Django 2.2.24 on 2021-07-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('types', models.CharField(choices=[('pdf', 'Pdf'), ('image', 'Image')], default='pdf', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('qcm', 'Qcm'), ('drag-drop', 'Drag-drop'), ('crossed-word', 'Crossed-word'), ('find-word', 'Find-word'), ('link-card', 'Link-card'), ('search-word', 'Search-word')], default='qcm', max_length=15)),
                ('data', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Course')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Formation')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.Formation'),
        ),
    ]
